# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167fhjt7C6BAjNM38zObMdRYLVGdUW6jF
"""

import pandas as pd
import numpy as np

# Müşterinin gönderdiği ham ve sorunlu veri seti simülasyonu
data = {
    'Siparis_ID': [101, 102, 103, 104, 105, 103, 106, 107, 108],
    'Urun': ['Kulaklık', 'Klavye', 'Mouse', 'Monitör', 'Kulaklık', 'Mouse', None, 'Klavye', 'Mouse'],
    'Adet': [2, 1, 3, None, 1, 3, 2, 2, -1],  # Eksik veri ve hatalı negatif adet var
    'Birim_Fiyat': [450, 850, 300, 3200, 450, 300, 1200, 850, 300]
}

df = pd.DataFrame(data)
print("Müşteriden gelen ham dosya:")
df

# 1. Tamamen tekrar eden (mükerrer) satırları kaldırıyoruz
df_temiz = df.drop_duplicates()

# 2. Ürün adı veya Adet bilgisi boş (None/NaN) olan satırları eliyoruz
df_temiz = df_temiz.dropna(subset=['Urun', 'Adet'])

# 3. Hatalı olan negatif veya 0 adetli siparişleri filtreliyoruz (Sadece Adet > 0 olanlar kalsın)
df_temiz = df_temiz[df_temiz['Adet'] > 0]

print("Temizlenmiş Veri:")
df_temiz

# 1. Satır bazında ciroyu (Toplam Tutar) hesaplayalım
df_temiz['Toplam_Tutar'] = df_temiz['Adet'] * df_temiz['Birim_Fiyat']

# 2. Ürün bazında gruplayıp toplam adet ve toplam ciroyu bulalım (Müşterinin istediği özet rapor)
rapor = df_temiz.groupby('Urun').agg({
    'Adet': 'sum',
    'Toplam_Tutar': 'sum'
}).reset_index()

# 3. Kolon isimlerini şık ve anlaşılır yapalım
rapor.columns = ['Ürün Adı', 'Toplam Satış Adedi', 'Toplam Ciro (TL)']

# 4. En çok ciro getiren üründen en aza doğru sıralayalım
rapor = rapor.sort_values(by='Toplam Ciro (TL)', ascending=False)

rapor